using System;
using System.Collections.Generic;

namespace Tedydev.PrekladIO
{
    public class LanguageItem
    {
        public string code;
        public string language;

    }

    public static class SupportedLanguages
    {

        public static List<LanguageItem> languageCodes = new List<LanguageItem> {
        new LanguageItem(){language = "Afrikaans", code = "af"},
        new LanguageItem(){language = "Albanian", code= "sq"},
        new LanguageItem(){language="Amharic", code="am"},
        new LanguageItem(){language="Arabic", code="ar"},
        new LanguageItem(){language="Armenian", code="hy"},
        new LanguageItem(){language="Assamese", code="as"},
        new LanguageItem(){language="Aymara", code="ay"},
        new LanguageItem(){language="Azerbaijani", code="az"},
        new LanguageItem(){language="Bambara", code="bm"},
        new LanguageItem(){language="Basque", code="eu"},
        new LanguageItem(){language="Belarusian", code="be"},
        new LanguageItem(){language="Bengali", code="bn"},
        new LanguageItem(){language="Bhojpuri", code="bho"},
        new LanguageItem(){language="Bosnian", code="bs"},
        new LanguageItem(){language="Bulgarian", code="bg"},
        new LanguageItem(){language="Catalan", code="ca"},
        new LanguageItem(){language="Cebuano", code="ceb"},
        new LanguageItem(){language="Chinese (Simplified)", code="zh-CN"},
        new LanguageItem(){language="Chinese (Simplified)", code="zh"},
        new LanguageItem(){language="Chinese (Traditional)", code="zh-TW"},
        new LanguageItem(){language="Corsican", code="co"},
        new LanguageItem(){language="Croatian", code="hr"},
        new LanguageItem(){language="Czech", code="cs"},
        new LanguageItem(){language="Danish", code="da"},
        new LanguageItem(){language="Dhivehi", code="dv"},
        new LanguageItem(){language="Dogri", code="doi"},
        new LanguageItem(){language="Dutch", code="nl"},
        new LanguageItem(){language="English", code="en"},
        new LanguageItem(){language="Esperanto", code="eo"},
        new LanguageItem(){language="Estonian", code="et"},
        new LanguageItem(){language="Ewe", code="ee"},
        new LanguageItem(){language="Filipino (Tagalog)", code="fil"},
        new LanguageItem(){language="Finnish", code="fi"},
        new LanguageItem(){language="French", code="fr"},
        new LanguageItem(){language="Frisian", code="fy"},
        new LanguageItem(){language="Galician", code="gl"},
        new LanguageItem(){language="Georgian", code="ka"},
        new LanguageItem(){language="German", code="de"},
        new LanguageItem(){language="Greek", code="el"},
        new LanguageItem(){language="Guarani", code="gn"},
        new LanguageItem(){language="Gujarati", code="gu"},
        new LanguageItem(){language="Haitian Creole", code="ht"},
        new LanguageItem(){language="Hausa", code="ha"},
        new LanguageItem(){language="Hawaiian", code="haw"},
        new LanguageItem(){language="Hebrew", code="he"},
        new LanguageItem(){language="Hebrew", code="iw"},
        new LanguageItem(){language="Hindi", code="hi"},
        new LanguageItem(){language="Hmong", code="hmn"},
        new LanguageItem(){language="Hungarian", code="hu"},
        new LanguageItem(){language="Icelandic", code="is"},
        new LanguageItem(){language="Igbo", code="ig"},
        new LanguageItem(){language="Ilocano", code="ilo"},
        new LanguageItem(){language="Indonesian", code="id"},
        new LanguageItem(){language="Irish", code="ga"},
        new LanguageItem(){language="Italian", code="it"},
        new LanguageItem(){language="Japanese", code="ja"},
        new LanguageItem(){language="Javanese", code="jv"},
        new LanguageItem(){language="Javanese", code="jw"},
        new LanguageItem(){language="Kannada", code="kn"},
        new LanguageItem(){language="Kazakh", code="kk"},
        new LanguageItem(){language="Khmer", code="km"},
        new LanguageItem(){language="Kinyarwanda", code="rw"},
        new LanguageItem(){language="Konkani", code="gom"},
        new LanguageItem(){language="Korean", code="ko"},
        new LanguageItem(){language="Krio", code="kri"},
        new LanguageItem(){language="Kurdish", code="ku"},
        new LanguageItem(){language="Kurdish (Sorani)", code="ckb"},
        new LanguageItem(){language="Kyrgyz", code="ky"},
        new LanguageItem(){language="Lao", code="lo"},
        new LanguageItem(){language="Latin", code="la"},
        new LanguageItem(){language="Latvian", code="lv"},
        new LanguageItem(){language="Lingala", code="ln"},
        new LanguageItem(){language="Lithuanian", code="lt"},
        new LanguageItem(){language="Luganda", code="lg"},
        new LanguageItem(){language="Luxembourgish", code="lb"},
        new LanguageItem(){language="Macedonian", code="mk"},
        new LanguageItem(){language="Maithili", code="mai"},
        new LanguageItem(){language="Malagasy", code="mg"},
        new LanguageItem(){language="Malay", code="ms"},
        new LanguageItem(){language="Malayalam", code="ml"},
        new LanguageItem(){language="Maltese", code="mt"},
        new LanguageItem(){language="Maori", code="mi"},
        new LanguageItem(){language="Marathi", code="mr"},
        new LanguageItem(){language="Meiteilon (Manipuri)", code="mni-Mtei"},
        new LanguageItem(){language="Mizo", code="lus"},
        new LanguageItem(){language="Mongolian", code="mn"},
        new LanguageItem(){language="Myanmar (Burmese)", code="my"},
        new LanguageItem(){language="Nepali", code="ne"},
        new LanguageItem(){language="Norwegian", code="no"},
        new LanguageItem(){language="Nyanja (Chichewa)", code="ny"},
        new LanguageItem(){language="Odia (Oriya)", code="or"},
        new LanguageItem(){language="Oromo", code="om"},
        new LanguageItem(){language="Pashto", code="ps"},
        new LanguageItem(){language="Persian", code="fa"},
        new LanguageItem(){language="Polish", code="pl"},
        new LanguageItem(){language="Portuguese (Portugal, Brazil)", code="pt"},
        new LanguageItem(){language="Punjabi", code="pa"},
        new LanguageItem(){language="Quechua", code="qu"},
        new LanguageItem(){language="Romanian", code="ro"},
        new LanguageItem(){language="Russian", code="ru"},
        new LanguageItem(){language="Samoan", code="sm"},
        new LanguageItem(){language="Sanskrit", code="sa"},
        new LanguageItem(){language="Scots Gaelic", code="gd"},
        new LanguageItem(){language="Sepedi", code="nso"},
        new LanguageItem(){language="Serbian", code="sr"},
        new LanguageItem(){language="Sesotho", code="st"},
        new LanguageItem(){language="Shona", code="sn"},
        new LanguageItem(){language="Sindhi", code="sd"},
        new LanguageItem(){language="Sinhala (Sinhalese)", code="si"},
        new LanguageItem(){language="Slovak", code="sk"},
        new LanguageItem(){language="Slovenian", code="sl"},
        new LanguageItem(){language="Somali", code="so"},
        new LanguageItem(){language="Spanish", code="es"},
        new LanguageItem(){language="Sundanese", code="su"},
        new LanguageItem(){language="Swahili", code="sw"},
        new LanguageItem(){language="Swedish", code="sv"},
        new LanguageItem(){language="Tagalog (Filipino)", code="tl"},
        new LanguageItem(){language="Tajik", code="tg"},
        new LanguageItem(){language="Tamil", code="ta"},
        new LanguageItem(){language="Tatar", code="tt"},
        new LanguageItem(){language="Telugu", code="te"},
        new LanguageItem(){language="Thai", code="th"},
        new LanguageItem(){language="Tigrinya", code="ti"},
        new LanguageItem(){language="Tsonga", code="ts"},
        new LanguageItem(){language="Turkish", code="tr"},
        new LanguageItem(){language="Turkmen", code="tk"},
        new LanguageItem(){language="Twi (Akan)", code="ak"},
        new LanguageItem(){language="Ukrainian", code="uk"},
        new LanguageItem(){language="Urdu", code="ur"},
        new LanguageItem(){language="Uyghur", code="ug"},
        new LanguageItem(){language="Uzbek", code="uz"},
        new LanguageItem(){language="Vietnamese", code="vi"},
        new LanguageItem(){language="Welsh", code="cy"},
        new LanguageItem(){language="Xhosa", code="xh"},
        new LanguageItem(){language="Yiddish", code="yi"},
        new LanguageItem(){language="Yoruba", code="yo"},
        new LanguageItem(){language="Zulu", code="zu"}};

        public static bool isExist(String code)
        {
            var result = languageCodes.Find(l => l.code == code);
            return result != null;
        }
    }

}

